#! /bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

# present working directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# addes path to bashrc script to users /.bashrc
log_daemon_msg "Setting up ~/.bashrc aliases..."
echo "source $DIR/bashrc" >> ~/.bashrc
log_end_msg 0

# Aliases and functions will now be able to be used
log_daemon_msg "Sourcing ~/.bashrc..."
echo `source ~/.bashrc` > /dev/null
log_end_msg 0
